### ISSUE TITLE
As I user I want to have quick filter options on the whiskey page

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#12]
# Overview
Whiskey drinks will want to be able to filter the whiskies that they want to see. They should be able to filter based on the country of origin/region, the type of whiskey, coloured, chill-filtered, age statement and ABV/proof

# Tasks

- [x] https://github.com/aaronsnig501/drams/projects/1#card-67828474
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67828496
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67828574
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67828603
