### ISSUE TITLE
As a user I want to see the details of a whiskey

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#20]
# Overview
A user should be able to click on a whiskey and be able to see a page dedicated to that whiskey

# Tasks

- [ ] https://github.com/aaronsnig501/drams/projects/1#card-67962703
- [ ] https://github.com/aaronsnig501/drams/projects/1#card-67962715
- [ ] https://github.com/aaronsnig501/drams/projects/1#card-67962742
- [ ] https://github.com/aaronsnig501/drams/projects/1#card-67962955
