### ISSUE TITLE
As a user I want to see the details of a whiskey

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#25]
# Overview
A user should be able to click on a whiskey and be able to see a page dedicated to that whiskey

# Tasks

- [x] https://github.com/aaronsnig501/drams/projects/1#card-67962703
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67962715
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67962742
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67962955
