### ISSUE TITLE
As a user I want to add a new whiskey

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#26]
# Overview
A user should be able to create a new whiskey

# Tasks

- [x] https://github.com/aaronsnig501/drams/projects/1#card-67963994
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67964132
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67964156
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67964188
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67964246
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67964268
