### ISSUE TITLE
As a user I want to limit amount the of results per page

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#33]
# Overview
Implement pagination in order to shorten the list of results required to be returned and rendered from the server

# Tasks

- [x] https://github.com/aaronsnig501/drams/projects/1#card-67965022
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67965032
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67965041
