### ISSUE TITLE
As a user I want to search for whiskies

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#4]
# Overview
Add the ability to search for whiskies on the whiskey page. User's should be able to search for a whiskey or brand.

# Constraints
This should use the same search code as the home page

# Tasks
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67827882
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67827861
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67827841
