### ISSUE TITLE
As a user I want to be able to read reviews for whiskies

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#77]
# Overview
All users should be able to see reviews for whiskies

# Tasks

- [ ] [BE: Update whiskey serializer to retrieve review data](https://github.com/aaronsnig501/drams/projects/1#card-69150612)
- [ ] [FE: Implement the design on the whiskey page](https://github.com/aaronsnig501/drams/projects/1#card-69150632)
- [ ] [FE: Implement API calls](https://github.com/aaronsnig501/drams/projects/1#card-69150642)
