### ISSUE TITLE
As a user I want to sort whiskey results

### ISSUE THREAD

**Issue by aaronsnig501** [aaronsnig501/drams#8]
# Overview
Users should have the ability to order whiskey results by name, brand name, age statement, ABV/proof

# Tasks

- [x] https://github.com/aaronsnig501/drams/projects/1#card-67827979
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67827994
- [x] https://github.com/aaronsnig501/drams/projects/1#card-67828019
